#!/bin/bash

echo "ID     CPU     MEM     TOTAL     UPTIME"

info=$(/usr/bin/ruby /opt/openvz-snmp-extend/src/cloud_vm_monitoring/scripts/vmm/kvm/poll)
virsh -c qemu:///system list | grep one- | while read vm; do
    deploy_id=$(echo $vm | cut -d' ' -f 2)
    id=$(echo $deploy_id | cut -d- -f 2)
    cpu=$(echo $info | sed -r 's/.*\one-'$id'usedcpu=*//' | sed  's/\usedmemory.*//')
    status_str=$(echo $vm | cut -d' ' -f 3)
    used_mem=$(virsh --connect qemu:///system --readonly dominfo `echo $deploy_id` | grep "Used memory:" | cut -d' ' -f6)
    max_mem=$(virsh --connect qemu:///system --readonly dominfo `echo $deploy_id` | grep "Max memory:" | cut -d' ' -f7)
    uuid=$(virsh --connect qemu:///system --readonly dominfo `echo $deploy_id` | grep "UUID:" | cut -d' ' -f12)
    tuuid=$(echo [`echo ${uuid:0:1}`]`echo ${uuid:1}`)
#    used_cpu=$(/bin/ps aux | grep `echo $tuuid` | cut -c17-20)
    processid=$(/bin/ps aux | grep `echo $tuuid` | cut -c10-15)
    time=$(/bin/ps -p $processid -o etime= | tr -d ' ')
    uptime=$(case ${#time} in "8") echo ${time: -2}+${time: -5:2}*60+${time: -8:2}*3600 | bc;;  "5")  echo ${time: -2}+${time: -5:2}*60 | bc;; *) echo $(echo $time | cut -d'-' -f1)*86400+${time: -2}+${time: -5:2}*60+${time: -8:2}*3600 | bc;; esac)
     
    if [ $status_str == "running" ]; then
        state="a"
    else
        state="e"
    fi
echo "$id     $cpu     $used_mem     $max_mem     $uptime"
done
